fileVersion: 1
id: "532"
mappingDefinitions:
  SOURCE:
    database: RUHULAMINS_DEV
    schema: SOURCE_DATA
  STAGE:
    database: RUHULAMIN_QA
    schema: TARGET2
  TARGET:
    database: RUHULAMIN_QA
    schema: TARGET
name: New Environment
type: Environment
